figure;
plot(tout, yout(:, 1), '-b',...
     tout, 0.98*yout(:, 2), ':k',...
     tout, 1.02*yout(:, 2), ':k',...
     tout, yout(:, 2), '--k');
% Find 2% settling time.
[wee1, ind] = findpeaks(-abs(yout(:, 1) - 0.98*yout(:, 2)));
ts = ind(1);
[s, wee2] = sprintf('\\uparrow \\newline Settling time: %ds', ts);
text(ts, yout(ts, 1), s,...
     'HorizontalAlignment', 'left',...
     'VerticalAlignment', 'top');
% Find overshoot
[wee3, ind] = max(yout(:, 1));
to = ind(1);
[s, wee4] = sprintf('Overshoot: %.2f%% \\newline \\downarrow',...
                    100*(yout(to, 1)/yout(to, 2) - 1));
text(to, yout(to, 1), s,...
     'HorizontalAlignment', 'left',...
     'VerticalAlignment', 'bottom');